FROM cgr.dev/chainguard-private/chainguard-base AS runner

WORKDIR /app

RUN apk add --no-cache openjdk-21

# Explicitly set JAVA_HOME for the OpenJDK installed by apk
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
ENV PATH="$JAVA_HOME/bin:$PATH"
RUN echo "JAVA_HOME=$JAVA_HOME" && java -version && javac -version

# Set the entrypoint to run the Java application
ENTRYPOINT ["java"]

